== To create a new project based on this template
* Follow the directions on this wiki page: https://github.com/commoncriteria/pp-template/wiki/Creating-a-New-Project
* Edit the README contents below, replacing QQQQ with the name of your requirements document, and replacing all occurrences of "pp-template" with the name of your new repo.

== Protection Profile for QQQQ
== Functional Package for QQQQ
== Protection Profile Module for QQQQ

image:https://img.shields.io/badge/Build-master-black.svg[Master Badges]
image:https://github.com/commoncriteria/pp-template/workflows/Build/badge.svg[Build]
image:https://github.com/commoncriteria/pp-template/workflows/Validate/badge.svg[Validate]

image:https://raw.githubusercontent.com/commoncriteria/pp-template/gh-pages/build-branch-badge.svg[Last
QuickBuilt Branch]
https://github.com/commoncriteria/pp-template/blob/gh-pages/ValidationReport.txt[image:https://raw.githubusercontent.com/commoncriteria/pp-template/gh-pages/validation.svg[Validation]]
https://github.com/commoncriteria/pp-template/blob/gh-pages/SanityChecksOutput.md[image:https://raw.githubusercontent.com/commoncriteria/pp-template/gh-pages/warnings.svg[SanityChecks]]
https://github.com/commoncriteria/pp-template/blob/gh-pages/SpellCheckReport.txt[image:https://raw.githubusercontent.com/commoncriteria/pp-template/gh-pages/spell-badge.svg[SpellCheck]]
https://commoncriteria.github.io/pp-template[image:https://github.com/commoncriteria/pp-template/actions/workflows/quick_build.yml/badge.svg[QuickBuild]]

https://github.com/commoncriteria/pp-template/issues[image:https://img.shields.io/github/issues/commoncriteria/pp-template.svg?maxAge=2592000[GitHub
issues Open]]
image:https://img.shields.io/badge/license-Unlicensed-blue.svg[license]

=== Draft Version (latest build of master branch)

* https://commoncriteria.github.io/pp-template/master/pp-template-release-linkable.html[Protection
Profile for QQQQ] (html)
* https://commoncriteria.github.io/pp-template/master/pp-template-release-linkable.pdf[Protection
Profile for QQQQ] (pdf)

=== Release Version

* link:QQQQ[Protection Profile for QQQQ]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/QQQQ/issues[repository issue tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/qqqq.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.
You shouldn’t need to modify it.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
