== Protection Profile Template

=== Quickstart

[arabic]
. To make a new protection profile create a new repo through
the web interface.
- Go to ```github.com/orgs/commoncriteria```
- Select the Repositories tab
- New Repository
- Name it (e.g. widget)
- Make it public
- add a README file

. To continue, you need a command line interface. This can be your local Linux subsystem, or using a tool such as Git Extensions.

. Clone the pp-template repo 
....
# Make a bare clone of the pp-template repository
git clone --bare https://github.com/commoncriteria/pp-template.git
cd pp-template.git

# This can also be done through the Git Extentions GUI by cloning
# the pp-template repo and selecting the --bare checkbox.
````

. Push the pp-template contents into your new repo
````
# Mirror-push to the new repository (where widget is the name of
# the repo you created in step 1).
# In Git Extensions use the Console to do this.
git push --mirror http://github.com/commoncriteria/widget.git
````

. Optionally remove the local copy of the pp-template repo
````
cd ..
rm -rf pp-template.git
....

[arabic, start=3]
. Do a full clone of your new project
````
git clone --recursive http://github.com/commoncriteria/widget.git

# Or use Git Extensions to clone the repo
````

. Rename your local copy of the main XML file in the input directory
from pp-template.xml to widget.xml (or whatever the name of your project is).
+
If something was the project name it would be,
+
....
git mv input/pp-template.xml input/something.xml
....

. If creating a PP-Module rename Module.make to Makefile
otherwise rename ProtectionProfile.make to Makefile and delete the other
.make file.
. If creating a Protection Profile Module open input/something.xml and
change the opening <PP> and closing </PP> tags to be <Module> and
</Module> respectively. If you’re creating a standard Protection Profile
then these tags do not need to be changed.
. Remove this content from the readme, up to the line below and
customize (look for `QQQQ' and `pp-template').

Note: Adding this project to the Travis CI live build requires special
permission and cannot be done without assistance. Contact the the
framework coordinators for more informatino.

For more information see the
https://github.com/commoncriteria/pp-template/wiki[PP Development Wiki].

'''''

== Protection Profile or Extended Package for QQQQ

image:https://img.shields.io/badge/Build-master-black.svg[Master Badges]
image:https://github.com/commoncriteria/pp-template/workflows/Build/badge.svg[Build]
image:https://github.com/commoncriteria/pp-template/workflows/Validate/badge.svg[Validate]

image:https://raw.githubusercontent.com/commoncriteria/pp-template/gh-pages/build-branch-badge.svg[Last
QuickBuilt Branch]
https://github.com/commoncriteria/pp-template/blob/gh-pages/ValidationReport.txt[image:https://raw.githubusercontent.com/commoncriteria/pp-template/gh-pages/validation.svg[Validation]]
https://github.com/commoncriteria/pp-template/blob/gh-pages/SanityChecksOutput.md[image:https://raw.githubusercontent.com/commoncriteria/pp-template/gh-pages/warnings.svg[SanityChecks]]
https://github.com/commoncriteria/pp-template/blob/gh-pages/SpellCheckReport.txt[image:https://raw.githubusercontent.com/commoncriteria/pp-template/gh-pages/spell-badge.svg[SpellCheck]]
https://commoncriteria.github.io/pp-template[image:https://github.com/commoncriteria/pp-template/actions/workflows/quick_build.yml/badge.svg[QuickBuild]]

https://github.com/commoncriteria/pp-template/issues[image:https://img.shields.io/github/issues/commoncriteria/pp-template.svg?maxAge=2592000[GitHub
issues Open]]
image:https://img.shields.io/badge/license-Unlicensed-blue.svg[license]

This repository hosts the draft version of the Protection Profile for
QQQQ based on the
https://commoncriteria.github.io/pp/QQQQ/QQQQ-esr.html[Essential
Security Requirements (ESR)] for this technology class of products. This
repository is used to facilitate collaboration and development on the
draft document. See the link:#Release-Version[release] section if you
are looking for the officially released version for evaluations. A list
of products that have passed evaluation against this Protection Profile
can be found link:QQQQ[here].

=== Draft Version

* https://commoncriteria.github.io/pp/QQQQ/QQQQ-release.html[Protection
Profile for QQQQ] (html)
* https://commoncriteria.github.io/pp/QQQQ/QQQQ-release.pdf[Protection
Profile for QQQQ] (pdf)

=== Release Version

* link:QQQQ[Protection Profile for QQQQ]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/QQQQ/issues[repository issue tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/qqqq.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.
You shouldn’t need to modify it.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
